version: '3.4'

services:
  orin:
    image: RoboSub_2026
    network_mode: "host"
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined   
    volumes:
      - ../:/home/david/ws/RoboSub_2026
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev:/dev
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USERNAME: david
        USER_UID: 1000
    command: /bin/sh -c "while sleep 1000; do :; done"